### ISSUE TITLE
Litter not shown on city-map

### ISSUE THREAD

**Issue by FredMark** [OpenLitterMap/openlittermap-web#112]
I guess this has got something to do with OpenStreetMap, but not sure, so let me post it anyway,
if we can do something with it (maybe even with OSM itself?), that could help, maybe.

I live in Krommenie and i have picked a lot of litter in my city.
However, if you go to the city Krommenie, all you see is the litter that was found on the bicyclepath between the city Krommenie and Assendelft.
This is not correct, there should be way more data.

However, if you go to 'Zaanstad', which is more like a big region with several cities, you find all the data, and as you can see, a lot of that data is plotted on the city Krommenie.
So actually, this data should not be shown with Zaanstad, but with Krommenie.

(Or, if there is a good reason to show all this data under Zaanstad, then at least also the data from the cyclingpath should not be under Krommenie, but also under Zaanstad.)
![Schermafdruk 2020-12-24_11 47 09 (irfanview)](https://user-images.githubusercontent.com/2518047/103084572-9d0f9600-45df-11eb-8924-6c0cf4f9cfc6.jpg)

**Comment by xlcrr** [comment]
This is partly due to OSM address values and partly due to how we interpret them.

See [CheckLocations.php](https://github.com/OpenLitterMap/openlittermap-web/blob/master/app/CheckLocations.php)

This is executed every time a geotagged image is uploaded. 

If the values exist, we select them and add to it.

If not, OpenLitterMap will add a new location to the database.

Each location (Country, State, City) has an ID and a name. We check for the name, and add the ID to the photos table. eg country_id = 1 , state_id = 6, city_id = 100.

If we want to change what location existing photos are saved to, we need to update the location_id values on photos table

and we might need to update how we check for locations and select them too.

**Comment by xlcrr** [comment]
This will be done soon, it's on trello
