### ISSUE TITLE
Profile-page, some texts should be white for better reading ability

### ISSUE THREAD

**Issue by FredMark** [OpenLitterMap/openlittermap-web#165]
see printscreen,
some texts are already changed to while, which makes it much better to read, but some are still in the old style.
![Schermafdruk 2021-01-24_19 27 15 (irfanview)](https://user-images.githubusercontent.com/2518047/105639797-7bbdf600-5e7a-11eb-98cb-2d9e09476e50.jpg)

**Comment by GeniJaho** [comment]
I think that the purple color is selected as a secondary color so that the whole page won't simply be composed of white text. However, since the background of the cards is also dark purple, I googled these colors that might look good on them. Which one to use? I personally like the second, seems fresh :D 

![image](https://user-images.githubusercontent.com/29065651/125489679-1082adef-a77b-4b3b-b443-4265c10e74c1.png)
![image](https://user-images.githubusercontent.com/29065651/125489943-a4ad9d89-8d70-465f-b3fe-e6cb12ef61cc.png)
![image](https://user-images.githubusercontent.com/29065651/125490079-02c01ddc-697e-4a09-bb72-263bd24297e0.png)
![image](https://user-images.githubusercontent.com/29065651/125490346-601d082f-d3f4-4275-ac59-e34272eb2f45.png)


We can also unify all the cards in a title + subtitle style, where the Title is in White and the subtitle is in secondary color (or vice-versa). @FredMark @xlcrr what do you think?

**Comment by xlcrr** [comment]
Number 2 is cool

Once we get a few things sorted out we will revisit all this
